### ISSUE TITLE
Build errors (webpack generating source map)

### ISSUE THREAD

**Issue by theWebalyst** [linkeddata/mashlib#9]
OS: Debian (jesse)...

I cloned, did `npm install` and then `node_modules/webpack/bin/webpack.js`

It goes quiet for a minute and then:

```
$ node_modules/webpack/bin/webpack.js 
/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (native)
    at /home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (native)
    at Compilation.<anonymous> (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (/home/mrh/src/solid/linkeddata-mashlib/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/Compilation.js:670:11)
    at next (/home/mrh/src/solid/linkeddata-mashlib/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/home/mrh/src/solid/linkeddata-mashlib/node_modules/babel-minify-webpack-plugin/dist/index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (/home/mrh/src/solid/linkeddata-mashlib/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/Compilation.js:666:10)
    at Compilation.applyPluginsAsyncSeries (/home/mrh/src/solid/linkeddata-mashlib/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/Compilation.js:662:9)
    at Compilation.applyPluginsAsyncSeries (/home/mrh/src/solid/linkeddata-mashlib/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/Compilation.js:605:8)
    at applyPluginsParallel.err (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/Compiler.js:508:17)
    at /home/mrh/src/solid/linkeddata-mashlib/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/mrh/src/solid/linkeddata-mashlib/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by dmitrizagidulin** [comment]
Thanks for the heads up! What version Node are you using?

**Comment by theWebalyst** [comment]
v6.11.5

**Comment by melvincarvalho** [comment]
I tried with v6.1.0 on ubuntu 16.04 (also debian based) and it works

```
> webpack --progress --colors

Hash: 8b5936513a90f0619f59                                                              
Version: webpack 3.6.0
Time: 199911ms
             Asset     Size  Chunks                    Chunk Names
    mashlib.min.js  1.82 MB       0  [emitted]  [big]  main
mashlib.min.js.map  4.89 MB       0  [emitted]         main
   [4] (webpack)/buildin/global.js 509 bytes {0} [built]
   [6] (webpack)/buildin/module.js 517 bytes {0} [built]
 [253] multi ./index.js 28 bytes {0} [built]
 [254] ./index.js 1.67 kB {0} [built]
 [258] (webpack)/buildin/amd-options.js 82 bytes {0} [built]
 [259] ./node_modules/n3/lib ^\.\/N3.*$ 407 bytes {0} [built]
    + 517 hidden modules
```

**Comment by melvincarvalho** [comment]
Tricky one!

Possibly related?

https://github.com/webpack/webpack/issues/5931

**Comment by theWebalyst** [comment]
Melvin is correct, workaround:

```
"devDependencies": {
    "webpack-sources": "1.0.1"
```
In package.json, then `npm install` and now `npm run build` works for me.

**Comment by timbl** [comment]
I think we can close this one now.   I think also in general we are not supporting Node 6 in future because of webpack issues.
